// GENERATED by scripts/stamp-versions.ts — do not edit by hand.
// The form-context-react-zod version this demo is built against. Source of
// truth is the repo root package.json; run `bun run stamp-versions` to refresh.
export const version = '3.0.0';
