/**
 * Stamp the library version (from root package.json — the single source of
 * truth) into a generated `version.ts` in each demo, so the web and native
 * demos can display which version of form-context-react-zod they're running.
 *
 * The generated files are committed (like the README version line) and
 * regenerated here; build:lib runs this before every demo command, so they
 * stay in sync without anyone editing them by hand.
 *
 * Alternative if you'd rather not track generated output: gitignore the two
 * targets below (e.g. `/version.ts` in examples/web/.gitignore and
 * `/src/version.ts` in examples/native/.gitignore). The trade-off is that a
 * fresh checkout won't compile until this script has run — fine in practice
 * since build:lib (which runs it) precedes every demo command.
 *
 * Adapted from Unirend's version-stamping scripts (keverw/unirend). Run via
 * `bun run stamp-versions` (also runs as part of build:lib).
 */
import fs from 'node:fs';
import path from 'node:path';

const rootDir = path.resolve(import.meta.dir, '..');

const pkg = JSON.parse(
  fs.readFileSync(path.join(rootDir, 'package.json'), 'utf8')
) as { version: string };

// Each demo gets a generated `version.ts` next to its source. Paths are
// relative to the repo root.
const targets = ['examples/web/version.ts', 'examples/native/src/version.ts'];

const contents = `// GENERATED by scripts/stamp-versions.ts — do not edit by hand.
// The form-context-react-zod version this demo is built against. Source of
// truth is the repo root package.json; run \`bun run stamp-versions\` to refresh.
export const version = '${pkg.version}';
`;

for (const target of targets) {
  const filePath = path.join(rootDir, target);
  fs.writeFileSync(filePath, contents);
  console.log(`✅ stamp-versions: ${target} -> v${pkg.version}`);
}
